# Generated by Django 4.0.9 on 2023-07-13 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields
import service_onfido.enums
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('secret', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('manager_groups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=80), blank=True, default=list, null=True, size=10)),
                ('active', models.BooleanField(default=True)),
                ('payout_exclusion_period', models.IntegerField(default=0)),
                ('payout_day', models.IntegerField(default=4)),
                ('payout_hour', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('token', models.CharField(max_length=200, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service_onfido.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='admin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_company', to='service_onfido.user'),
        ),
        migrations.CreateModel(
            name='PlatformWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('identifier', models.CharField(max_length=64, unique=True)),
                ('event', enumfields.fields.EnumField(blank=True, enum=service_onfido.enums.WebhookEvent, max_length=100, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('completed', models.DateTimeField(null=True)),
                ('failed', models.DateTimeField(null=True)),
                ('tries', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_onfido.company')),
            ],
            options={
                'unique_together': {('identifier', 'company')},
            },
        ),
    ]
