# Generated by Django 4.1.10 on 2023-10-16 13:10

from django.db import migrations, models
import enumfields.fields
import service_onfido.enums


class Migration(migrations.Migration):
    dependencies = [
        ("service_onfido", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="status",
            field=enumfields.fields.EnumField(
                default="initiating",
                enum=service_onfido.enums.CheckStatus,
                max_length=50,
            ),
        ),
        migrations.AddConstraint(
            model_name="check",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(("status", service_onfido.enums.CheckStatus["PROCESSING"]))
                ),
                fields=("user", "status"),
                name="unique_processing_check_per_user",
            ),
        ),
    ]
