# Generated by Django 4.1.10 on 2023-09-11 12:18

from django.db import migrations, models
import enumfields.fields
import service_onfido.enums


class Migration(migrations.Migration):
    dependencies = [
        ("service_onfido", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="documenttype",
            name="document_type_unique_company_platform_type",
        ),
        migrations.RemoveConstraint(
            model_name="documenttype",
            name="document_type_unique_company_onfido_type",
        ),
        migrations.RemoveField(
            model_name="check",
            name="reports",
        ),
        migrations.AddField(
            model_name="documenttype",
            name="side",
            field=enumfields.fields.EnumField(
                blank=True,
                enum=service_onfido.enums.DocumentTypeSide,
                max_length=12,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="onfido_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name="documenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("side__isnull", False)),
                fields=("company", "platform_type", "onfido_type", "side"),
                name="unique_company_platform_type_onfido_type_side",
            ),
        ),
        migrations.AddConstraint(
            model_name="documenttype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("side__isnull", True)),
                fields=("company", "platform_type", "onfido_type"),
                name="unique_company_platform_type_onfido_type",
            ),
        ),
    ]
